### ISSUE TITLE
Excelent Job

### ISSUE THREAD

**Issue by andgarzonmal** [indigodavid/awesome-books#2]
![WellDoneGoodJobGIF](https://user-images.githubusercontent.com/95243996/170060900-35dd0f00-5879-4950-829f-f18f292152bc.gif)

- [ ] Awesome job, you can try to disable the linters related to the last function as you are calling the function on the HTML

**Comment by indigodavid** [comment]
Thanks for your comments. The latest implementation solves that issue.
